apiVersion: concord.dev/v1
kind: Control

metadata:
  id: ISO27001-A.5.6-contact-with-special-interest-groups
  name: iso27001-a-5-6-contact-with-special-interest-groups
  title: Appropriate contacts with special interest groups are maintained
  framework: iso27001
  severity: low
  tags: []
  owners:
    - team: concord-dev

spec:
  description: |
    TODO: describe what ISO27001-A.5.6-contact-with-special-interest-groups enforces.

  evidence:
    - id: iso27001_a_5_6_contact_with_special_interest_groups
      source: attestation
      type: policy_attestation
      fixture: ../tests/fixtures/iso27001-a-5-6-contact-with-special-interest-groups-pass.json
      params:
              schema: TODO  # e.g. ropa-v1, dpia-v1, dpa-v1, ism-v1
              signers:
                - dpo@acme.com
              max_age_days: 365

  policy:
    engine: rego
    package: concord.iso27001.iso27001_a_5_6_contact_with_special_interest_groups
    file: ../policies/iso27001-a-5-6-contact-with-special-interest-groups.rego

  remediation:
    runbook: docs/remediation/iso27001-a-5-6-contact-with-special-interest-groups.md
    auto_fix: false
    estimated_effort: 30m

  status: draft
  blocking: false
